[workspace]
resolver = "3"
members = [
    "crates/z13helper-client",
    "crates/z13helper-core",
    "crates/z13helper",
    "crates/z13helperd",
    "crates/z13helperctl",
]
default-members = ["crates/z13helper"]

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT"
version = "1.0.1"
repository = "https://github.com/UHDbits/z13helper"

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.19"
anyhow = "1.0.104"
libc = "0.2.189"
signal-hook = "0.4.4"
tracing = "0.1.44"
zbus = "5.18.0"
