name: Nix

on:
  push:
    branches: [main, master]
    paths:
      - .github/workflows/nix.yml
      - flake.nix
      - flake.lock
      - nix/**
      - Cargo.toml
      - Cargo.lock
      - crates/*/Cargo.toml
      - crates/z13helperd/bpf/**
      - assets/**
      - contrib/**
      - Makefile
  pull_request:
    branches: [main, master]
    paths:
      - .github/workflows/nix.yml
      - flake.nix
      - flake.lock
      - nix/**
      - Cargo.toml
      - Cargo.lock
      - crates/*/Cargo.toml
      - crates/z13helperd/bpf/**
      - assets/**
      - contrib/**
      - Makefile
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: nix-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix flake check -L
